<?= HTML::anchor('admin/index', '<strong>หน้าหลัก admin</strong>'); ?> |
<?= HTML::anchor('admin/sms', '<strong>ส่ง sms</strong>'); ?> |
<?= HTML::anchor('admin/user', '<strong>สมาชิกอาสา</strong>'); ?> |
<?= HTML::anchor('admin/organization', '<strong>สมาชิกองกร</strong>'); ?> |
<?= HTML::anchor('admin/event', '<strong>งานอาสา</strong>'); ?> |
<?= HTML::anchor('admin/comment', '<strong>คอมเมนต์</strong>'); ?> |
<?= HTML::anchor('admin/training', '<strong>ฝีกอบรม</strong>'); ?> |
<?= HTML::anchor('admin/knowledge', '<strong>ความรู้</strong>'); ?> |
<?= HTML::anchor('admin/news', '<strong>ข่าว</strong>'); ?> |
<?= HTML::anchor('admin/help', '<strong>ช่วยเหลือ (help)</strong>'); ?> - | -
<?= HTML::anchor('admin/setting', '<strong>ระบบแนะนำงานอาสา (Matching)</strong>'); ?> 